name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Cache Bun
        uses: actions/cache@v4
        with:
          path: |
            ${{ runner.tool_cache }}/bun
            .bun
          key: windows-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            windows-bun-

      - name: Install dependencies
        run: |
          bun install --production
          bun remove sharp
          bun add sharp@latest --platform=win32 --arch=x64 --no-save
          bun add sharp@latest --platform=win32 --arch=x64

      - name: Build executable
        run: |
          bun build --compile --target=bun-windows-x64 --minify ./src/index.ts --outfile bulk-image-zipper-${{ github.ref_name }}.exe --no-sourcemap

      - name: Debug Info
        shell: pwsh
        run: |
          Write-Host "Tag: ${{ github.ref_name }}"
          Write-Host "Event name: ${{ github.event_name }}"
          Write-Host "Actor: ${{ github.actor }}"
          $file = Get-Item -Path "bulk-image-zipper-${{ github.ref_name }}.exe"
          $sizeMB = [math]::Round($file.Length / 1MB, 2)
          Write-Host "File size: $sizeMB MB"

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: bulk-image-zipper-${{ github.ref_name }}.exe
          generate_release_notes: true
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: false
          prerelease: false
